name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        node-version: [10, 12, 13]
    steps:
    - uses: actions/checkout@master
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache npm
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        npm run test
